name: Full history calendar

on:
  # Schedule daily updates
  schedule: [{cron: "0 */6 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  full-calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: ryanbakker/metrics@master
        with:
          filename: metrics.plugin.calendar.full.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0
