name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 16 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
          - uses: ryanbakker/metrics@master
            name: Repositories traffic
            with:
              filename: metrics.plugin.traffic.svg
              token: ${{ secrets.METRICS_TOKEN }}
              base: repositories
              plugin_traffic: yes
  
