name: Update Contribution Calendar

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  update-calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: ryanbakker/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # The username of the owner of the repository
          username: ryanbakker
          # The name of the repository
          repository: ryanbakker
          # The name of the branch to update
          branch: main
          # The path to the README.md file
          path: README.md
          # The section to update
          section: calendar
